// https://react-icons.github.io/react-icons/
// Font Awesome
export const faIcons = [
	// 矢印
	'FaRegArrowAltCircleDown',
	'FaRegArrowAltCircleLeft',
	'FaRegArrowAltCircleRight',
	'FaRegArrowAltCircleUp',
	'FaRegCaretSquareDown',
	'FaRegCaretSquareLeft',
	'FaRegCaretSquareRight',
	'FaRegCaretSquareUp',

	'FaArrowAltCircleDown',
	'FaArrowAltCircleLeft',
	'FaArrowAltCircleRight',
	'FaArrowAltCircleUp',
	'FaArrowCircleDown',
	'FaArrowCircleLeft',
	'FaArrowCircleRight',
	'FaArrowCircleUp',

	'FaAngleDoubleDown',
	'FaAngleDoubleLeft',
	'FaAngleDoubleRight',
	'FaAngleDoubleUp',
	'FaAngleDown',
	'FaAngleLeft',
	'FaAngleRight',
	'FaAngleUp',
	'FaArrowDown',
	'FaArrowLeft',
	'FaArrowRight',
	'FaArrowUp',

	'FaCaretDown',
	'FaCaretLeft',
	'FaCaretRight',
	'FaCaretUp',

	'FaArrowsAltH',
	'FaArrowsAltV',
	'FaArrowsAlt',

	'FaMarsDouble',
	'FaMarsStrokeH',
	'FaMarsStrokeV',
	'FaMarsStroke',
	'FaMars',
	'FaPlayCircle',
	'FaPlay',
	'FaRedoAlt',
	'FaRedo',
	'FaReplyAll',
	'FaReply',
	'FaShareSquare',
	'FaShare',
	'FaSignInAlt',
	'FaSignOutAlt',
	'FaSortAlphaDownAlt',
	'FaSortAlphaDown',
	'FaSortAlphaUpAlt',
	'FaSortAlphaUp',
	'FaSortAmountDownAlt',
	'FaSortAmountDown',
	'FaSortAmountUpAlt',
	'FaSortAmountUp',
	'FaSortDown',
	'FaSortNumericDownAlt',
	'FaSortNumericDown',
	'FaSortNumericUpAlt',
	'FaSortNumericUp',
	'FaSort',
	'FaStepBackward',
	'FaStepForward',
	'FaUndo',

	'FaRegCheckCircle',
	'FaRegCheckSquare',
	'FaRegCircle',

	'FaRegCommentDots',
	'FaRegComment',
	'FaRegComments',

	'FaRegEnvelopeOpen',
	'FaRegEnvelope',

	'FaRegFileAlt',
	'FaRegFileArchive',
	'FaRegFileAudio',
	'FaRegFileCode',
	'FaRegFileImage',
	'FaRegFilePdf',
	'FaRegFolder',
	'FaRegFolderOpen',

	'FaRegQuestionCircle',

	// device
	'FaMobileAlt',
	'FaTabletAlt',
	'FaDesktop',
	'FaLaptop',

	// Logo
	'FaGoogle',
	'FaAmazon',
	'FaApple',
	'FaFacebookF',
	'FaFacebookMessenger',
	'FaFacebookSquare',
	'FaFacebook',
	'FaInstagramSquare',
	'FaInstagram',
	'FaMicrosoft',
	'FaTwitter',
	'FaXTwitter',
	'FaBloggerB',
	'FaDropbox',
	'FaEvernote',
	'FaLine',
	'FaLinkedinIn',
	'FaLinkedin',
	'FaSkype',
	'FaSlackHash',
	'FaSlack',
	'FaTiktok',
	'FaSoundcloud',
	'FaTrello',
	'FaTwitch',
	'FaTwitterSquare',

	// 一般的なツール？
	'FaGoogleDrive',
	'FaYoutubeSquare',
	'FaYoutube',
	'FaDailymotion',
	'FaVimeoV',
	'FaVimeo',
	'FaPinterestP',
	'FaPinterestSquare',
	'FaPinterest',
	'FaPlaystation',

	// browser
	'FaChrome',
	'FaEdge',
	'FaFirefoxBrowser',
	'FaFirefox',
	'FaInternetExplorer',

	// Web
	'FaHtml5',
	'FaCss3Alt',
	'FaCss3',
	'FaSass',
	'FaJsSquare',
	'FaJs',
	'FaMarkdown',
	'FaPhp',
	'FaLaravel',
	'FaBootstrap',
	'FaReact',
	'FaReacteurope',
	'FaDocker',
	'FaGitAlt',
	'FaGitSquare',
	'FaGit',
	'FaGithubAlt',
	'FaGithubSquare',
	'FaGithub',
	'FaGitkraken',
	'FaGitlab',
	'FaFontAwesomeFlag',
	'FaFontAwesomeAlt',
	'FaGrunt',
	'FaGulp',
	'FaJava',
	'FaLinux',
	'FaNodeJs',
	'FaNode',
	'FaNpm',
	'FaPython',
	'FaSourcetree',
	'FaSwift',
	'FaUnity',
	'FaCodeBranch',
	'FaCode',

	// IT系ツール？
	'FaJsfiddle',
	'FaCodepen',
	'FaStackOverflow',
	'FaFigma',
	'FaSketch',
	'FaShopify',
	'FaMailchimp',
	'FaHubspot',
	'FaSpotify',
	'FaUnsplash',
	'FaWindows',
	'FaWix',
	'FaWordpressSimple',
	'FaWordpress',
	'FaYoast',
	'FaWpforms',
	'FaSistrix',

	'FaAd',

	'FaAddressBook',
	'FaAlignCenter',
	'FaAlignJustify',
	'FaAlignLeft',
	'FaAlignRight',
	'FaBars',
	'FaAnchor',
	'FaAward',
	'FaBalanceScale',
	'FaBatteryEmpty',
	'FaBatteryFull',
	'FaBatteryHalf',
	'FaBatteryQuarter',
	'FaBatteryThreeQuarters',
	'FaBeer',
	'FaBellSlash',
	'FaBell',
	'FaBirthdayCake',
	'FaCalendarAlt',
	'FaCog',
	'FaDownload',

	// 吹き出し
	'FaCommentAlt',
	'FaCommentDollar',
	'FaCommentDots',
	'FaCommentMedical',
	'FaCommentSlash',
	'FaComment',
	'FaCommentsDollar',
	'FaComments',

	// 乗り物
	'FaBusAlt',
	'FaBus',
	'FaCarAlt',
	'FaCarCrash',
	'FaCarSide',
	'FaCar',
	'FaMotorcycle',
	'FaPlaneArrival',
	'FaPlaneDeparture',
	'FaPlaneSlash',
	'FaPlane',
	'FaShip',
	'FaShippingFast',
	'FaShuttleVan',
	'FaSpaceShuttle',
	'FaSubway',
	'FaTaxi',
	'FaTrain',
	'FaTram',
	'FaTruckMonster',
	'FaTruckMoving',
	'FaTruckPickup',
	'FaTruck',

	// Ball
	'FaBaseballBall',
	'FaBasketballBall',
	'FaBicycle',
	'FaFootballBall',
	'FaSkating',
	'FaSkiingNordic',
	'FaSkiing',
	'FaSnowboarding',
	'FaSwimmer',
	'FaTableTennis',
	'FaTablets',
	'FaVolleyballBall',

	//school
	'FaChalkboardTeacher',
	'FaChalkboard',
	'FaChartArea',
	'FaChartBar',
	'FaChartLine',
	'FaChartPie',

	// weather
	'FaCloudMeatball',
	'FaCloudMoonRain',
	'FaCloudMoon',
	'FaCloudRain',
	'FaCloudShowersHeavy',
	'FaCloudSunRain',
	'FaCloudSun',
	'FaCloud',
	'FaSun',
	'FaTree',
	'FaWater',

	// animal
	'FaCrow',
	'FaDemocrat',
	'FaDog',
	'FaDragon',
	'FaFish',
	'FaFrog',
	'FaFutbol',

	//mail
	'FaEnvelopeOpenText',
	'FaEnvelopeOpen',
	'FaEnvelopeSquare',
	'FaEnvelope',

	'FaExclamationCircle',
	'FaExclamationTriangle',
	'FaExternalLinkAlt',
	'FaExternalLinkSquareAlt',
	'FaEyeDropper',
	'FaEyeSlash',
	'FaEye',

	//face
	'FaGrimace',
	'FaGrinAlt',
	'FaGrinBeamSweat',
	'FaGrinBeam',
	'FaGrinHearts',
	'FaGrinSquintTears',
	'FaGrinSquint',
	'FaGrinStars',
	'FaGrinTears',
	'FaGrinTongueSquint',
	'FaGrinTongueWink',
	'FaGrinTongue',
	'FaGrinWink',
	'FaGrin',
	'FaMehBlank',
	'FaMehRollingEyes',
	'FaMeh',
	'FaSadCry',
	'FaSadTear',
	'FaSmileBeam',
	'FaSmileWink',
	'FaSmile',
	'FaSurprise',
	'FaTired',
	'FaRegFrownOpen',
	'FaRegFrown',
	'FaRegGrimace',
	'FaRegGrinAlt',
	'FaRegGrinBeamSweat',
	'FaRegGrinBeam',
	'FaRegGrinHearts',
	'FaRegGrinSquintTears',
	'FaRegGrinSquint',
	'FaRegGrinStars',
	'FaRegGrinTears',
	'FaRegGrinTongueSquint',
	'FaRegGrinTongueWink',
	'FaRegGrinTongue',
	'FaRegGrinWink',
	'FaRegGrin',
	'FaRegSadCry',
	'FaRegSadTear',
	'FaRegSmileBeam',
	'FaRegSmileWink',
	'FaRegSmile',
	'FaRegSurprise',
	'FaRegTired',

	//hand
	'FaHandPointDown',
	'FaHandPointLeft',
	'FaHandPointRight',
	'FaHandPointUp',
	'FaHandPointer',
	'FaHandsHelping',
	'FaHands',
	'FaHandshakeAltSlash',
	'FaHandshakeSlash',
	'FaHandshake',
	'FaThumbsDown',
	'FaThumbsUp',
	'FaRegThumbsDown',
	'FaRegThumbsUp',

	// hourglass
	'FaHourglassStart',
	'FaHourglassHalf',
	'FaHourglassEnd',
	'FaHourglass',
	'FaStarHalfAlt',
	'FaStarHalf',
	'FaStar',
	'FaStarOfDavid',
	'FaStarOfLife',
	'FaRegStarHalf',
	'FaRegStar',
	'FaRegHandPaper',
	'FaRegHandPeace',
	'FaRegHandPointDown',
	'FaRegHandPointLeft',
	'FaRegHandPointRight',
	'FaRegHandPointUp',
	'FaRegHandPointer',
	'FaRegHandRock',
	'FaRegHandScissors',
	'FaRegHandSpock',
	'FaRegHandshake',
	'FaRegKissBeam',
	'FaRegKissWinkHeart',
	'FaRegKiss',
	'FaRegLaughBeam',
	'FaRegLaughSquint',
	'FaRegLaughWink',
	'FaRegLaugh',
	'FaRegMehBlank',
	'FaRegMehRollingEyes',
	'FaRegMeh',

	// map
	'FaMapMarkedAlt',
	'FaMapMarked',
	'FaMapMarkerAlt',
	'FaMapMarker',
	'FaMapPin',
	'FaMapSigns',
	'FaMap',

	// 機材
	'FaMicrophoneAltSlash',
	'FaMicrophoneAlt',
	'FaMicrophoneSlash',
	'FaMicrophone',
	'FaMicroscope',
	'FaMousePointer',
	'FaMouse',
	'FaPhoneAlt',
	'FaPhone',
	'FaPhoneSlash',
	'FaPhoneSquareAlt',
	'FaPhoneSquare',
	'FaPowerOff',
	'FaPrint',
	'FaVolumeDown',
	'FaVolumeMute',
	'FaVolumeOff',
	'FaVolumeUp',

	// pen
	'FaPenAlt',
	'FaPenFancy',
	'FaPenNib',
	'FaPenSquare',
	'FaPen',
	'FaPencilAlt',
	'FaPencilRuler',

	// money
	'FaMoneyBillAlt',
	'FaMoneyBillWaveAlt',
	'FaMoneyBillWave',
	'FaMoneyBill',
	'FaMoneyCheckAlt',
	'FaMoneyCheck',
	'FaPiggyBank',

	// Toilet トイレ
	'FaPoo',
	'FaPoop',
	'FaToiletPaper',
	'FaToilet',

	'FaSmokingBan',
	'FaSmoking',

	'FaQuestionCircle',
	'FaQuestion',
	'FaQuoteLeft',
	'FaQuoteRight',

	'FaSearchDollar',
	'FaSearchLocation',
	'FaSearchMinus',
	'FaSearchPlus',
	'FaSearch',

	'FaTag',
	'FaTags',
	'FaUnlink',
	'FaUnlockAlt',
	'FaUnlock',
	'FaUpload',

	'FaThermometerEmpty',
	'FaThermometerFull',
	'FaThermometerHalf',
	'FaThermometerQuarter',
	'FaThermometerThreeQuarters',
	'FaToggleOff',
	'FaToggleOn',
	'FaTrashAlt',

	// user
	'FaUser',
	'FaUsers',
	'FaUsersSlash',
	'FaVenusDouble',
	'FaVenusMars',
	'FaVenus',
];
